// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXElzWqL01VV38eB0lFZpIZG0Qqw7Z4to',
    appId: '1:665094536908:android:2ba7657965f36a09f40c69',
    messagingSenderId: '665094536908',
    projectId: 'notesapp-d1403',
    databaseURL: 'https://notesapp-d1403-default-rtdb.firebaseio.com',
    storageBucket: 'notesapp-d1403.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAJ39L0qjnI9f6iVTKwjUHl9qW9EZgfOw',
    appId: '1:665094536908:ios:b036ddfc20e91731f40c69',
    messagingSenderId: '665094536908',
    projectId: 'notesapp-d1403',
    databaseURL: 'https://notesapp-d1403-default-rtdb.firebaseio.com',
    storageBucket: 'notesapp-d1403.appspot.com',
    androidClientId: '665094536908-2j25ou9re6b1h5t9t0os8mfef1fl89ro.apps.googleusercontent.com',
    iosClientId: '665094536908-g58d16ur1nvie2v6ook4a1sjtcgro8cp.apps.googleusercontent.com',
    iosBundleId: 'com.example.ios.notes',
  );
}
